# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CocoaDebug' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #pod 'CocoaDebug', :configurations => ['Debug']
  pod 'CocoaDebug', :git => 'https://github.com/HiKarry/CocoaDebug.git', :tag => '2.0.4', :configurations => ['Debug']

end
